apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name}}
spec:
  type: ClusterIP
  selector:
    components: {{ .Values.postgres.component}}
  ports:
  - port: {{ .Values.postgres.port}}
    protocol: TCP
