app:
  component: frontend
  name: demo-app
  port: 80
  image: misterion96/demo-app
  version: latest

api:
  component: backend
  name: demo-api
  port: 3000
  image: misterion96/demo-api
  version: latest
  envs:
    - DATABASE_URL

postgres:
  component: db
  name: postgres
  port: 5432
  image: postgres
  version: 12.18-bullseye
  envs:
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD
